# fly.toml app configuration file generated for shift4shop on 2023-05-17T01:28:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shift4shop"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "lax"
processes = []

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  GITHUB_CLIENT_ID = "cf299537ab9ec9a3"
  GITHUB_CLIENT_SECRET = "60ec2e185914792e"
  GITHUB_DEPLOYMENT_KEY = "3721b6c074c85e481785"
  PHX_HOST = "shift4shop.fly.dev"
  PORT = "8080"
  SHIFT4SHOP_CLIENT_ID = "7edefd179423964c567ec777ee7d39b7"
  SHIFT4SHOP_CLIENT_SECRET = "feeb22fd6c5c4040a8eccb2a3ce742d6"
  STRIPE_API_KEY = "pk_test_51LjIVwGV3HzI6y8uTHMcHbM2GUvyUQftqsOIqMowuwlqx5BlG3K0PnxPmMvKlUy5oqLjPRknDDBOvIvrY9iWLnGz00SAEq7CFP"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
