defmodule Api.Repo.Migrations.CreateProducts do
  use Ecto.Migration

  def change do
    create table(:products) do
      add :skuinfo, :integer
      add :mfgid, :string
      add :short_description, :string
      add :manufacturer_id, :integer
      add :manufacturer_name, :string
      add :distributor_list, :string
      add :last_update, :string
      add :user_id, :string
      add :gtin, :string
      add :category_list, :string
      add :external_ids_list, :string
      add :category_external_ids_list, :string
      add :non_taxable, :string
      add :not_for_sale, :string
      add :hide, :string
      add :gift_certificate, :string
      add :home_special, :string
      add :category_special, :string
      add :non_searchable, :string
      add :gift_wrap_item, :string
      add :ship_cost, :float
      add :weight, :float
      add :height, :float
      add :width, :float
      add :depth, :float
      add :self_ship, :float
      add :free_shipping, :float
      add :reward_points, :integer
      add :redeem_points, :integer
      add :disable_rewards, :integer
      add :stock_alert, :integer
      add :reorder_quantity, :integer
      add :in_stock_message, :string
      add :out_of_stock_message, :string
      add :back_order_message, :string
      add :inventory_control, :string
      add :warehouse_location, :string
      add :warehouse_bin, :string
      add :warehouse_aisle, :string
      add :warehouse_custom, :string
      add :description, :string
      add :keywords, :string
      add :extra_field_1, :string
      add :extra_field_2, :string
      add :extra_field_3, :string
      add :extra_field_4, :string
      add :extra_field_5, :string
      add :extra_field_6, :string
      add :extra_field_7, :string
      add :extra_field_8, :string
      add :extra_field_9, :string
      add :extra_field_10, :string
      add :extra_field_11, :string
      add :extra_field_12, :string
      add :extra_field_13, :string
      add :feature_list, :string
      add :plugin_list, :string
      add :sample_enable, :string
      add :sample_name, :string
      add :sample_skuprefix, :string
      add :sample_price, :float
      add :sample_weight, :float
      add :review_average, :float
      add :review_count, :integer
      add :main_image_file, :string
      add :main_image_caption, :string
      add :thumbnail_file, :string
      add :media_file, :string
      add :additional_image_file_2, :string
      add :additional_image_caption_2, :string
      add :additional_image_file_3, :string
      add :additional_image_caption_3, :string
      add :additional_image_file_4, :string
      add :additional_image_caption_4, :string
      add :image_gallery_list, :string
      add :option_set_list, :string
      add :advanced_option_list, :string
      add :related_product_list, :string
      add :up_selling_item_list, :string
      add :discount_list, :string
      add :do_not_use_category_options, :string
      add :date_created, :string
      add :listing_template_id, :integer
      add :listing_template_name, :string
      add :login_required_option_id, :integer
      add :login_required_option_name, :string
      add :login_required_option_redirect_to, :string
      add :allow_access_customer_group_id, :integer
      add :allow_access_customer_group_name, :string
      add :rmamax_period, :string
      add :canonical_url, :string
      add :tax_code, :string
      add :display_text, :string
      add :minimum_quantity, :float
      add :maximum_quantity, :float
      add :allow_only_multiples, :float
      add :allow_fractional_quantity, :float
      add :quantity_options, :string
      add :group_options_for_quantity_pricing, :string
      add :apply_quantity_discount_to_options, :string
      add :enable_make_an_offer_feature, :string
      add :minimum_acceptable_offer, :string
      add :price_level_1, :float
      add :price_level_1_hide, :float
      add :price_level_2, :float
      add :price_level_2_hide, :float
      add :price_level_3, :float
      add :price_level_3_hide, :float
      add :price_level_4, :float
      add :price_level_4_hide, :float
      add :price_level_5, :float
      add :price_level_5_hide, :float
      add :price_level_6, :float
      add :price_level_6_hide, :float
      add :price_level_7, :float
      add :price_level_7_hide, :float
      add :price_level_8, :float
      add :price_level_8_hide, :float
      add :price_level_9, :float
      add :price_level_9_hide, :float
      add :price_level_10, :float
      add :price_level_10_hide, :float
      add :buy_button_link, :string
      add :product_link, :string
      add :title, :string
      add :custom_file_name, :string
      add :redirect_link, :string
      add :meta_tags, :string
      add :special_instructions, :string
      add :assign_key, :string
      add :re_use_keys, :string
      add :serial_list, :string
      add :eproduct_list, :string

      timestamps()
    end
  end
end
